name: aibot1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+2
  path_provider: ^2.0.9
  http: ^0.13.5
  image_picker: ^0.8.6+1
  gallery_saver: ^2.3.2
  tdesign_flutter: ^0.1.0
  permission_handler: ^10.2.0+1
  flutter_svg: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
